accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    SignUpView, 
    UserView, 
    UserUpdate,
    )

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
    email_template_name='registration/password_reset_email.html',
    success_url=reverse_lazy('accounts:password_reset_done'),
    ), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<user_id>/', UserView.as_view(), name="user_view"),
    path('<user_id>/edit/', UserUpdate.as_view(), name='user_update'),
    path('<user_id>/delete_profile_image/', UserUpdate.delete_profile_image, name='delete_profile_image'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import get_coins_markets, get_coin_by_id
from django.contrib.auth.decorators import login_required
from  django.views.decorators.cache  import never_cache
from ckeditor_uploader import views

urlpatterns = [
    path('idea/', include('idea.urls', namespace='idea')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts_conf'), namespace='accounts_conf')),
    path('prices/<int:page>/', get_coins_markets, name='prices_list'),
    path('price/<slug:id>/', get_coin_by_id, name='price_detail'),
    path('news/', include('news.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import (
    IdeaListView,
    IdeaDetailView, 
    LikeView,
    UnLikeView,
    CommentLikeView,
    CommentUnLikeView,
    IdeaUpdateView,
    IdeaCommentsUpdateView,
    IdeaDeleteView,
    IdeaCommentsDeleteView,
    IdeaCreateView,
    IdeaCommentsCreateView,
    )

app_name = 'idea'

urlpatterns = [
    path('<int:pk>/unlike-comment/', CommentUnLikeView, name='unlike_comment'),
    path('<int:pk>/like-comment/', CommentLikeView, name='like_comment'),
    path('<int:pk>/unlike-idea/', UnLikeView, name='unlike_idea'),
    path('<int:pk>/like-idea/', LikeView, name='like_idea'),
    path('<int:pk_idea>/comment_edit/<int:pk>/', IdeaCommentsUpdateView.as_view(), name='comment_edit'),
    path('<int:pk_idea>/comment-delete/<int:pk>/', IdeaCommentsDeleteView.as_view(), name='comment_delete'),
    path('<int:pk_idea>/new_comment/', IdeaCommentsCreateView.as_view(),name='comment_new'),
    path('new/', IdeaCreateView.as_view(), name='idea_new'),
    path('<int:pk>/edit/', IdeaUpdateView.as_view(), name='idea_edit'),
    path('<int:pk>/', IdeaDetailView.as_view(), name='idea_detail'),
    path('<int:pk>/delete/', IdeaDeleteView.as_view(), name='idea_delete'),
    path('', IdeaListView.as_view(), name='idea_list')
] 

handler404 = 'news.views.error_404'

news/models.py
from django.contrib.auth.models import User
from config.settings import AUTH_USER_MODEL
from django.conf import settings
from django.contrib.auth import get_user_model
from accounts.models import CustomUser
from django.db import models
from django.urls import  reverse
from ckeditor.fields import  RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    slug = models.CharField(max_length=300)


    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("news_new")


def get_header_image_filepath(self, filepath):
    return f'images/news/header/{self.author.id}/{self.header_image}'


class News(models.Model):

    class Meta:
        permissions = [
            ('all', 'all of the permissions')
        ]
        ordering = ['-datetime']

    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to=get_header_image_filepath)
    body = RichTextUploadingField()
    datetime = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ManyToManyField(Category, default='cryptocurrency', related_name='category')
    like_news = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_news')
    unlike_news = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_news_unlike')

    def total_likes(self):
        return self.like_news.count()

    def total_unlikes(self):
        return self.unlike_news.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news_detail", args=[str(self.id)])


class Comment(models.Model):
    news = models.ForeignKey(
        News, 
        on_delete=models.CASCADE,
        related_name='comments',
        )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    comment = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)

    like_comment = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_like')
    unlike_comment = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_unlike')

    def total_likes_comment(self):
        return self.like_comment.count()

    def total_unlikes_comment(self):
        return self.unlike_comment.count()

    class Meta:
        ordering = ['-created_on']
    

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.author)

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.news.id)])


# class Google_News(models.Model):

#     class Meta:
#         permissions = [
#             ('all', 'all of the permissions')
#         ]
#         ordering = ['-date_time']

#     title = models.CharField(max_length=355)
#     site = models.CharField(max_length=255)
#     description = models.TextField()
#     date_time = models.DateTimeField()
#     image = models.URLField(null=True, blank=True)
#     category = models.ManyToManyField(Category, related_name='category_google_news')

#     def __str__(self):
#         return self.title

templates/price/prices_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0", shrink-to-fit='no'>
    <title>{% block title %}Prices{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">CryptoLife</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'prices_list' page=1 %}">Prices <span class="sr-only">(current)</span></a>
          </li>
          {% if perms.news.add_news or perms.news.all %}
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              News
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'news_list' %}">News</a>
              <a class="dropdown-item" href="{% url 'news_new' %}">Create New News</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'news_list' %}">News<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'idea:idea_list' %}">Ideas<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
        {% if user.is_authenticated %}
        <div class = "btn-group dropleft">
          <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ user.profile_image.url }}" alt="logo" width="40" height="40">
          <div class="dropdown-menu" aria-labelledby="id_profile_links">
            <li class="dropdown-item">{{ user.username }}</li>
            <a class="dropdown-item" href="{% url 'accounts:user_view' user.id%}">Account</a>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
          </div>
        </div>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log In</a>
            <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
          {% endif %}
    </nav>
    <main>
      <div class='tableWrapper___3utdq cmc-table-homepage-wrapper___22rL4'>

        <table class="table table-hover cmc-table cmc-table___11lFC cmc-table-homepage___2_guh table " style="margin: auto;">
            <colgroup>
                <col style="width:20px;min-width:auto">
                <col style="width:200px;min-width:auto">
                <col style="width:84px;min-width:auto">
                <col style="width:84px;min-width:auto">
                <col style="width:200px;min-width:auto">
                <col style="width:200px;min-width:auto">
                <col style="width:200px;min-width:auto">

            </colgroup>
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">24h%</th>
                <th scope="col">Market Cap</th>
                <th scope="col">Volume(24h)</th>
                <th scope="col">Circulating Supply</th>
            </tr>
            </thead>
            <tbody>
              {% if data %}
                {% for obj in data %}
                  <tr>
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.market_cap_rank }}</a></td>
                    <td><img src={{obj.image}} height="35"> <a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.name }}</a> <a href="{% url 'price_detail' obj.id %}" style="color:rgb(63, 61, 61);">{{ obj.symbol }}</a></td>
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.current_price }}</a></td>
                    {% if obj.price_change_percentage_24h >= 0 %}
                      <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:rgb(0, 161, 0);"><span class="material-icons"  style="vertical-align: middle;">arrow_drop_up</span>{{ obj.price_change_percentage_24h }}</a></td>
                    {% else %}
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:red;"><span class="material-icons"  style="vertical-align: middle;">arrow_drop_down</span>{{ obj.price_change_percentage_24h }}</a></td>
                    {% endif %}
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.market_cap }}</a></td>
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.total_volume }}</a></td>
                    <td class="align-middle"><a href="{% url 'price_detail' obj.id %}" style="color:black;">{{ obj.circulating_supply }}</a></td>

                    
                  </tr>
                {% endfor %}
              {% else %}
                <h3>Notting here...</h3>
              {% endif %}
            </tbody>
        </table>

      </br>
      <p style='text-align:center;'>
        <a href="{% url 'prices_list' page=page|add:'-1' %}" style="color:black;"><span class="material-icons">arrow_back_ios</span></a>
        <a href="{% url 'prices_list' page=page|add:'1' %}" style="color:black;"><span class="material-icons">arrow_forward_ios</span></a>
      </p>
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>