accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    SignUpView, 
    UserView, 
    UserUpdate,
    )

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
    email_template_name='registration/password_reset_email.html',
    success_url=reverse_lazy('accounts:password_reset_done'),
    ), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<user_id>/', UserView.as_view(), name="user_view"),
    path('<user_id>/edit/', UserUpdate.as_view(), name='user_update'),
    path('<user_id>/delete_profile_image/', UserUpdate.delete_profile_image, name='delete_profile_image'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import get_coins_markets, get_coin_by_id
from django.contrib.auth.decorators import login_required
from  django.views.decorators.cache  import never_cache
from ckeditor_uploader import views

urlpatterns = [
    path('idea/', include('idea.urls', namespace='idea')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts_conf'), namespace='accounts_conf')),
    path('prices/<int:page>/', get_coins_markets, name='prices_list'),
    path('price/<slug:id>/', get_coin_by_id, name='price_detail'),
    path('news/', include('news.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import (
    IdeaListView,
    IdeaDetailView, 
    LikeView,
    UnLikeView,
    CommentLikeView,
    CommentUnLikeView,
    IdeaUpdateView,
    IdeaCommentsUpdateView,
    IdeaDeleteView,
    IdeaCommentsDeleteView,
    IdeaCreateView,
    IdeaCommentsCreateView,
    )

app_name = 'idea'

urlpatterns = [
    path('<int:pk>/unlike-comment/', CommentUnLikeView, name='unlike_comment'),
    path('<int:pk>/like-comment/', CommentLikeView, name='like_comment'),
    path('<int:pk>/unlike-idea/', UnLikeView, name='unlike_idea'),
    path('<int:pk>/like-idea/', LikeView, name='like_idea'),
    path('<int:pk_idea>/comment_edit/<int:pk>/', IdeaCommentsUpdateView.as_view(), name='comment_edit'),
    path('<int:pk_idea>/comment-delete/<int:pk>/', IdeaCommentsDeleteView.as_view(), name='comment_delete'),
    path('<int:pk_idea>/new_comment/', IdeaCommentsCreateView.as_view(),name='comment_new'),
    path('new/', IdeaCreateView.as_view(), name='idea_new'),
    path('<int:pk>/edit/', IdeaUpdateView.as_view(), name='idea_edit'),
    path('<int:pk>/', IdeaDetailView.as_view(), name='idea_detail'),
    path('<int:pk>/delete/', IdeaDeleteView.as_view(), name='idea_delete'),
    path('', IdeaListView.as_view(), name='idea_list')
] 

handler404 = 'news.views.error_404'

news/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import (
    NewsListView,
    NewsUpdateView,
    NewsDetailView,
    NewsDeleteView,
    NewsCreateView,
    NewsCommentsCreateView,
    NewsCommentsDeleteView,
    NewsCommentsUpdateView,
    CategoryCreatingView,
    # CategoryView,
    LikeView,
    UnLikeView,
    CommentLikeView,
    CommentUnLikeView,
    # google_news,
    )

urlpatterns = [
    # path('update/', google_news, name='update_news'),
    path('<int:pk>/unlike-comment/', CommentUnLikeView, name='unlike_comment'),
    path('<int:pk>/like-comment/', CommentLikeView, name='like_comment'),
    path('<int:pk>/unlike-news/', UnLikeView, name='unlike_news'),
    path('<int:pk>/like-news/', LikeView, name='like_news'),
    path('<int:pk_news>/comment_edit/<int:pk>/', NewsCommentsUpdateView.as_view(), name='comment_edit'),
    path('<int:pk_news>/comment-delete/<int:pk>/', NewsCommentsDeleteView.as_view(), name='comment_delete'),
    path('<int:pk_news>/new_comment/', NewsCommentsCreateView.as_view(),name='comment_new'),
    path('category/', CategoryCreatingView.as_view(), name='category_new'),
    # path('category/<slug:slug>/', CategoryView, name='category'),
    path('new/', NewsCreateView.as_view(), name='news_new'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='news_edit'),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('<int:pk>/delete', NewsDeleteView.as_view(), name='news_delete'),
    path('', NewsListView.as_view(), name='news_list')
] 

handler404 = 'news.views.error_404'

news/models.py
from django.contrib.auth.models import User
from config.settings import AUTH_USER_MODEL
from django.conf import settings
from django.contrib.auth import get_user_model
from accounts.models import CustomUser
from django.db import models
from django.urls import  reverse
from ckeditor.fields import  RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    slug = models.CharField(max_length=300)


    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("news_new")


def get_header_image_filepath(self, filepath):
    return f'images/news/header/{self.author.id}/{self.header_image}'


class News(models.Model):

    class Meta:
        permissions = [
            ('all', 'all of the permissions')
        ]
        ordering = ['-datetime']

    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to=get_header_image_filepath)
    body = RichTextUploadingField()
    datetime = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ManyToManyField(Category, default='cryptocurrency', related_name='category')
    like_news = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_news')
    unlike_news = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_news_unlike')

    def total_likes(self):
        return self.like_news.count()

    def total_unlikes(self):
        return self.unlike_news.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news_detail", args=[str(self.id)])


class Comment(models.Model):
    news = models.ForeignKey(
        News, 
        on_delete=models.CASCADE,
        related_name='comments',
        )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    comment = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)

    like_comment = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_like')
    unlike_comment = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_unlike')

    def total_likes_comment(self):
        return self.like_comment.count()

    def total_unlikes_comment(self):
        return self.unlike_comment.count()

    class Meta:
        ordering = ['-created_on']
    

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.author)

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.news.id)])


# class Google_News(models.Model):

#     class Meta:
#         permissions = [
#             ('all', 'all of the permissions')
#         ]
#         ordering = ['-date_time']

#     title = models.CharField(max_length=355)
#     site = models.CharField(max_length=255)
#     description = models.TextField()
#     date_time = models.DateTimeField()
#     image = models.URLField(null=True, blank=True)
#     category = models.ManyToManyField(Category, related_name='category_google_news')

#     def __str__(self):
#         return self.title

news/forms.py
from django import forms
from django.forms import fields, widgets
from .models import News, Comment


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'header_image', 'body', 'category')

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'}),
            'category' : forms.SelectMultiple(attrs={'class':'form-control'}),

        }

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

        widgets = {
            'comment' : forms.Textarea(attrs={'class':'form-control'})
        }

templates/news/categories.html
{% extends 'base.html' %}

{% block title %}{{slug}}{% endblock title %}

{% block content %}
    <h1>{{ slug }}</h1>
    {% for news in category_news %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold"><a href="{% url 'news_detail' news.pk %}" style="color:#1d1414;">{{ news.title }}</a></span> &middot;
                <span class="text-muted">by {{ news.author }} | {{ news.date }}</span>
            </div>
            <div class="card-body">
                {{ news.body|safe|truncatewords:"100" }}
            </div>
            {% if user == news.author or perms.news.all or perms.news.change_news or perms.news.delete_news %}
                <div class="card-footer text-center text-muted">
                        <a href="{% url 'news_edit' news.pk %}">Edit</a> | 
                        <a href="{% url 'news_delete' news.pk %}">Delete</a>
                    </div>
            {% endif %}
        </div>
        <br />
    {% endfor %}

{% endblock content %}

templates/news/category_new.html
{% extends 'base.html' %}

{% block title %}New Category{% endblock title %}

{% block content %}
    <h1>Add Category</h1>
    <br/>
    <div class="form-group">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>
    </div>
{% endblock content %}

templates/news/comment_news_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}New news{% endblock title %}

{% block content %}
    <h1>Comment New</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/news/news_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ news.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/news/news_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="news-entry">
        <h2>{{ object.title }}</h2>
        <p class="font-weight"><strong>by {{ object.author }} </strong> <span class="text-muted font-weight-normal">{{ object.datetime }}</span>
            {% if user.is_authenticated and user.id == news.author.id or perms.news.all or perms.news.change_news or perms.news.delete_news %} 
                <l style="font-size: 15px;">
                    (<a href="{% url 'news_edit' news.pk %}">Edit</a> | <a href="{% url 'news_delete' news.pk %}">Delete</a>)
                </l>
            {% endif %}
        {% if user.is_authenticated %}
            <div style='display:flex;'>
                <form action="{% url 'like_news' news.pk %}" method="POST">
                    {% csrf_token %}
                    {% if user in object.like_news.all %}
                    <button type="submit" name="news_id" value="{{ news.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_up</span> {{ total_likes }}</button>
                    {% else %}
                    <button type="submit" name="news_id" value="{{ news.id }}" class="btn"><span class="material-icons">thumb_up</span> {{ total_likes }}</button>
                    {% endif %}
                </form>

                <form action="{% url 'unlike_news' news.pk %}" method="POST">
                    {% csrf_token %}
                    {% if user in object.unlike_news.all %}
                    <button type="submit" name="news_id" value="{{ news.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_down</span> {{ total_unlikes }}</button> 
                    {% else %}
                    <button type="submit" name="news_id" value="{{ news.id }}" class="btn"><span class="material-icons">thumb_down</span> {{ total_unlikes }}</button>
                    {% endif %}
                </form>
            </div>
        {% else %}
        <small>
            {{ total_likes }} Likes & {{ total_unlikes }} Unlike | 
           <a href="{% url 'accounts:login' %}" class="">Log in</a> to like</small>
        {% endif %}
        </p>
        <hr>
        {% if object.header_image %}<br/>    
            <a href="{{ object.header_image.url }}"><img style="display: block; margin-left: auto; margin-right: auto; width: 100%;" src="{{ object.header_image.url }}" ></a><br/><br/>
        {% endif %}
        {{ object.body|safe|linebreaksbr }}
    </div>
    <br/>
    <p>
        {% for category in object.category.all.values %}
            {% if category.slug != 'cryptocurrency'  %}
                <a href="{% url 'price_detail' category.slug %}"><button type="button" class="btn btn-secondary">{{category.slug}}</button></a>
            {% endif %}
        {% endfor %}
        </p>
        <br/>
        <hr>

        <br/>
    <div class="col-md-8 card mb-4 mt-3">
        {% if user.is_authenticated %}
        <a href='{% url "comment_new" pk_news=news.pk %}'>Add comment ...</a>
        {% else %}
        <p><a href="{% url 'accounts:login' %}" class="">Log in</a> to add comment</p>
        {% endif %}
        <div class="card-body">
            <h2>{{ object.comments.count }} comments</h2>
            <hr>
            {% for comment in object.comments.all %}
            <div class="comments" style="padding: 10;">
                <p class="font-weight">
                    <strong>by {{ comment.author }}</strong>
                    <span class="text-muted font-weight-normal">
                        {{ comment.created_on }}
                    </span>
                    {% if user.is_authenticated and user.id == comment.author.id %} 
                        <l style="font-size: 15px;">
                            (<a href="{% url 'comment_edit'  pk_news=news.pk pk=comment.pk %}">Edit</a> | <a href="{% url 'comment_delete'  pk_news=news.pk pk=comment.pk %}">Delete</a>)
                        </l>
                    {% elif perms.news.all or perms.news.change_news or perms.news.delete_news %}
                        <l style="font-size: 15px;">
                            (<a href="{% url 'comment_delete'  pk_news=news.pk pk=comment.pk %}">Delete</a>)
                        </l>
                    {% endif %}
                </p>
                {{ comment.comment|safe|linebreaks }}
                {% if user.is_authenticated %}
                <div style='display:flex;'>
                    <form action="{% url 'like_comment' news.pk %}" method="POST">
                        {% csrf_token %}
                        {% if user in comment.like_comment.all %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_up</span> {{ comment.total_likes_comment }}</button>
                        {% else %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons">thumb_up</span> {{ comment.total_likes_comment }}</button>
                        {% endif %}
                    </form>

                    <form action="{% url 'unlike_comment' news.pk %}" method="POST">
                        {% csrf_token %}
                        {% if user in comment.unlike_comment.all %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_down</span> {{ comment.total_unlikes_comment }}</button> 
                        {% else %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons">thumb_down</span> {{ comment.total_unlikes_comment }}</button> 
                        {% endif %}
                    </form>
                </div>
                {% else %}
                <small>
                    {{ comment.total_likes_comment }} Likes & {{ comment.total_unlikes_comment }} Unlike | 
                    <a href="{% url 'accounts:login' %}" class="">Log in</a> to like</small>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock content %}

templates/news/news_edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock title %}

{% block content %}
    <h1>Edit</h1>
    <div class="form-group">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p}}
            <button class="btn btn-info ml-2" type="submit">Update</button>
        </form>
    </div>
{% endblock content %}

templates/news/news_list.html
{% extends 'base.html' %}

{% block title %}News{% endblock title %}

{% block content %}
</br>

    {% for news in news_cryptocurrency %}

        {% if news.pk %}

            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-3">
                        <img src="/media/{{news.img}}" class="card-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'news_detail' news.pk %}" style="color:#1d1414;">
                                    {{ news.title }}
                                </a>
                                
                                {% if user.is_authenticated and user.id == news.author.id or perms.news.all or perms.news.change_news or perms.news.delete_news %} 
                                <l style="font-size: 15px;">
                                    (<a href="{% url 'news_edit' news.pk %}">Edit</a> | <a href="{% url 'news_delete' news.pk %}">Delete</a>)
                                </l>
                                {% endif %}
                            </h5>
                            <span class="text-muted">by {{ news.site }} | {{ news.datetime }}</span>
                            <p class="card-text">{{ news.desc|safe|truncatewords:"200" }}</p>
                            <p class="card-text"><small class="text-muted">{{news.date}}</small></p>
                        </div>
                    </div>
                </div>
            </div>

        {% else %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="{{news.img}}" class="card-img">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><a href='https://{{news.link}}' style="color:#1d1414;">{{ news.title }}</a></h5>
                        <span class="text-muted">by {{ news.site }} | {{ news.datetime }}</span>
                        <p class="card-text"></br>{{ news.desc|safe|truncatewords:"200" }}</p>
                        <p class="card-text"><small class="text-muted">{{news.date}}</small></p>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}

    {% endfor %}

{% endblock content %}

templates/news/news_new.html
{% extends 'base.html' %}

{% block title %}New news{% endblock title %}

{% block content %}
    <h1>Add a news</h1>
    <br/>
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>
    </div>
{% endblock content %}