accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    SignUpView, 
    UserView, 
    UserUpdate,
    )

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
    email_template_name='registration/password_reset_email.html',
    success_url=reverse_lazy('accounts:password_reset_done'),
    ), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<user_id>/', UserView.as_view(), name="user_view"),
    path('<user_id>/edit/', UserUpdate.as_view(), name='user_update'),
    path('<user_id>/delete_profile_image/', UserUpdate.delete_profile_image, name='delete_profile_image'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import get_coins_markets, get_coin_by_id
from django.contrib.auth.decorators import login_required
from  django.views.decorators.cache  import never_cache
from ckeditor_uploader import views

urlpatterns = [
    path('idea/', include('idea.urls', namespace='idea')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts_conf'), namespace='accounts_conf')),
    path('prices/<int:page>/', get_coins_markets, name='prices_list'),
    path('price/<slug:id>/', get_coin_by_id, name='price_detail'),
    path('news/', include('news.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import (
    IdeaListView,
    IdeaDetailView, 
    LikeView,
    UnLikeView,
    CommentLikeView,
    CommentUnLikeView,
    IdeaUpdateView,
    IdeaCommentsUpdateView,
    IdeaDeleteView,
    IdeaCommentsDeleteView,
    IdeaCreateView,
    IdeaCommentsCreateView,
    )

app_name = 'idea'

urlpatterns = [
    path('<int:pk>/unlike-comment/', CommentUnLikeView, name='unlike_comment'),
    path('<int:pk>/like-comment/', CommentLikeView, name='like_comment'),
    path('<int:pk>/unlike-idea/', UnLikeView, name='unlike_idea'),
    path('<int:pk>/like-idea/', LikeView, name='like_idea'),
    path('<int:pk_idea>/comment_edit/<int:pk>/', IdeaCommentsUpdateView.as_view(), name='comment_edit'),
    path('<int:pk_idea>/comment-delete/<int:pk>/', IdeaCommentsDeleteView.as_view(), name='comment_delete'),
    path('<int:pk_idea>/new_comment/', IdeaCommentsCreateView.as_view(),name='comment_new'),
    path('new/', IdeaCreateView.as_view(), name='idea_new'),
    path('<int:pk>/edit/', IdeaUpdateView.as_view(), name='idea_edit'),
    path('<int:pk>/', IdeaDetailView.as_view(), name='idea_detail'),
    path('<int:pk>/delete/', IdeaDeleteView.as_view(), name='idea_delete'),
    path('', IdeaListView.as_view(), name='idea_list')
] 

handler404 = 'news.views.error_404'

idea/models.py
from config.settings import AUTH_USER_MODEL
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import  reverse
from ckeditor_uploader.fields import RichTextUploadingField
from news.models import Category


class Idea(models.Model):

    class Meta:
        permissions = [
            ('all', 'all of the permissions')
        ]
        ordering = ['-datetime']

    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/idea/header/")
    body = RichTextUploadingField()
    datetime = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ManyToManyField(Category, related_name='category_idea')
    like_idea = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_like')
    unlike_idea = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='the_like_unlike')

    def total_likes(self):
        return self.like_idea.count()

    def total_unlikes(self):
        return self.unlike_idea.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("idea:idea_detail", args=[str(self.id)])


class CommentIdea(models.Model):
    idea = models.ForeignKey(
        Idea, 
        on_delete=models.CASCADE,
        related_name='comments_idea',
        )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    comment_idea = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)

    like_comment_idea = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_idea_like')
    unlike_comment_idea = models.ManyToManyField(AUTH_USER_MODEL, blank=True, related_name='comment_idea_unlike')

    def total_likes_comment(self):
        return self.like_comment_idea.count()

    def total_unlikes_comment(self):
        return self.unlike_comment_idea.count()

    class Meta:
        ordering = ['-created_on']
    

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment_idea, self.author)

    def get_absolute_url(self):
        return reverse('idea:idea_detail', args=[str(self.idea.id)])

idea/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Idea, CommentIdea


class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = ('title', 'header_image', 'body', 'category')

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'}),
            'category' : forms.SelectMultiple(attrs={'class':'form-control'}),

        }

    
class CommentIdeaForm(forms.ModelForm):
    class Meta:
        model = CommentIdea
        fields = ('comment_idea',)

        widgets = {
            'comment_idea' : forms.Textarea(attrs={'class':'form-control'})
        }

idea/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Idea, CommentIdea
from .forms import IdeaForm, CommentIdeaForm
from datetime import datetime
from accounts.models import CustomUser
import json

class IdeaListView(ListView):
    model = Idea
    template_name = 'idea/idea_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(IdeaListView, self).get_context_data()
        idea_obj = Idea.objects.all().values()
        for idea in idea_obj:
            idea['datetime'] = idea['datetime'].replace(tzinfo=None)
            date = datetime.now() - idea['datetime']
            hours, remainder = divmod(date.total_seconds(), 3600)
            minutes, seconds = divmod(remainder, 60)
            if hours != 0:
                idea['date'] = str(int(hours)) + ' ' + 'hours ago'
            elif minutes != 0:
                idea['date'] = str(int(minutes)) + ' ' + 'minutes ago'
            else:
                idea['date'] = str(int(seconds)) + ' ' + 'seconds ago'

            idea['author'] = CustomUser.objects.get(id = idea['author_id'])

        context['ideas'] = idea_obj
            
        return context


class IdeaDetailView(DetailView):
    model = Idea
    template_name = 'idea/idea_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(IdeaDetailView, self).get_context_data(**kwargs)
        stuff = get_object_or_404(Idea, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        total_unlikes = stuff.total_unlikes()
        liked = False
        if stuff.like_idea.filter(id =self.request.user.id).exists():
            liked = True
        unliked = False
        if stuff.unlike_idea.filter(id =self.request.user.id).exists():
            unliked = True
        context["total_likes"] = total_likes
        context["total_unlikes"] = total_unlikes
        context["liked"] = liked
        context["unliked"] = unliked
        getobjector404 = True
        try:
            stuff_comment = get_object_or_404(CommentIdea, id=self.kwargs['pk'])
        except:
            getobjector404 = False
        if getobjector404 == True:
            stuff_comment = get_object_or_404(CommentIdea, id=self.kwargs['pk'])
            total_likes_comment = stuff_comment.total_likes_comment()
            total_unlikes_comment = stuff_comment.total_unlikes_comment()
            liked_comment = False
            if stuff_comment.like_comment_idea.filter(id =self.request.user.id).exists():
                liked_comment = True
            unliked_comment = False
            if stuff_comment.unlike_comment_idea.filter(id =self.request.user.id).exists():
                unliked_comment = True
            context["total_likes_comment"] = total_likes_comment
            context["total_unlikes_comment"] = total_unlikes_comment
            context["liked_comment"] = liked_comment
            context["unliked_comment"] = unliked_comment

        return context


def LikeView(request, pk):
    idea = get_object_or_404(Idea, id=request.POST.get('idea_id'))
    liked = False
    if idea.like_idea.filter(id=request.user.id).exists():
        idea.like_idea.remove(request.user)
        liked = False
    elif idea.unlike_idea.filter(id=request.user.id).exists():
        idea.unlike_idea.remove(request.user)
        idea.like_idea.add(request.user)
        unliked = False
    else:
        idea.like_idea.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('idea:idea_detail', args=[str(pk)]))


def UnLikeView(request, pk):
    idea = get_object_or_404(Idea, id=request.POST.get('idea_id'))
    unliked = False
    if idea.unlike_idea.filter(id=request.user.id).exists():
        idea.unlike_idea.remove(request.user)
        unliked = False
    elif idea.like_idea.filter(id=request.user.id).exists():
        idea.like_idea.remove(request.user)
        idea.unlike_idea.add(request.user)
        liked = False
    else:
        idea.unlike_idea.add(request.user)
        unliked = True
    
    return HttpResponseRedirect(reverse('idea:idea_detail', args=[str(pk)]))


def CommentLikeView(request, pk):
    comment = get_object_or_404(CommentIdea, id=request.POST.get('comment_id'))
    liked = False
    if comment.like_comment_idea.filter(id=request.user.id).exists():
        comment.like_comment_idea.remove(request.user)
        liked = False
    elif comment.unlike_comment_idea.filter(id=request.user.id).exists():
        comment.unlike_comment_idea.remove(request.user)
        comment.like_comment_idea.add(request.user)
        unliked = False
    else:
        comment.like_comment_idea.add(request.user)
        liked = True
    
    return HttpResponseRedirect(reverse('idea:idea_detail', args=[str(comment.idea.id)]))

def CommentUnLikeView(request, pk):
    comment = get_object_or_404(CommentIdea, id=request.POST.get('comment_id'))
    unliked = False
    if comment.unlike_comment_idea.filter(id=request.user.id).exists():
        comment.unlike_comment_idea.remove(request.user)
        unliked = False
    elif comment.like_comment_idea.filter(id=request.user.id).exists():
        comment.like_comment_idea.remove(request.user)
        comment.unlike_comment_idea.add(request.user)
        liked = False
    else:
        comment.unlike_comment_idea.add(request.user)
        unliked = True
    
    return HttpResponseRedirect(reverse('idea:idea_detail', args=[str(comment.idea.id)]))


class IdeaUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Idea
    form_class = IdeaForm
    template_name = 'idea/idea_edit.html'

    def get_success_url(self):
        return reverse_lazy('idea:idea_detail', args=[str(self.object.id)])

    def test_func(self):
        obj = self.get_object()
        if obj.author == self.request.user:
            return True 


class IdeaCommentsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CommentIdea
    fields = ('comment_idea',)
    template_name = 'idea/comment_edit.html'

    def get_absolute_url(self):
        return reverse_lazy('idea:idea_detail', args=[str(self.object.idea.id)])

    def get_object(self, *__, **___):
        return CommentIdea.objects.get(pk=self.kwargs['pk'])

    def test_func(self):
        obj = self.get_object()
        if obj.author == self.request.user:
            return True 



class IdeaDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Idea
    template_name = 'idea/idea_delete.html'
    success_url = reverse_lazy('idea:idea_list')

    def test_func(self):
        obj = self.get_object()
        if self.request.user.has_perm('idea:idea.all') or self.request.user.has_perm('idea.delete_idea') or obj.author.id == self.request.user.id:
            return True 


class IdeaCommentsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CommentIdea
    template_name = 'idea/comment_delete.html'
    
    def get_success_url(self):
        return reverse_lazy('idea:idea_detail', args=[str(self.object.idea.id)])

    def form_valid(self, form):
        form.instance.idea_id = self.kwargs['pk']
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        if self.request.user.has_perm('idea.all') or self.request.user.has_perm('idea.delete_idea') or obj.author == self.request.user:
            return True 



class IdeaCreateView(LoginRequiredMixin, CreateView):
    model = Idea
    form_class = IdeaForm
    template_name = 'idea/idea_new.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class IdeaCommentsCreateView(LoginRequiredMixin, CreateView):
    model = Idea
    template_name = 'idea/comment_idea_new.html'
    form_class = CommentIdeaForm

    def get_success_url(self):
        return reverse_lazy('idea:idea_detail', args=[str(self.object.idea.id)])


    def form_valid(self, form):
        form.instance.idea_id = self.kwargs['pk_idea']
        form.instance.author = self.request.user
        return super().form_valid(form)

templates/idea/comment_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete this comment?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/idea/comment_edit.html
{% extends 'base.html' %}

{% block title %}Edit Comment{% endblock title %}

{% block content %}
    <h1>Edit Comment</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>
{% endblock content %}

templates/idea/comment_idea_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}New news{% endblock title %}

{% block content %}
    <h1>Comment New</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/idea/idea_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ idea.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/idea/idea_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="news-entry">
        <h2>{{ object.title }}</h2>
        <p class="font-weight"><strong>by {{ object.author }} </strong> <span class="text-muted font-weight-normal">{{ object.datetime }}</span>
            {% if user.is_authenticated and user.id == idea.author.id %} 
                <l style="font-size: 15px;">
                    (<a href="{% url 'idea:idea_edit' idea.id %}">Edit</a> | <a href="{% url 'idea:idea_delete' idea.id %}">Delete</a>)
                </l>
            {% elif perms.idea.all or perms.idea.change_idea or perms.idea.delete_idea %}
                <l style="font-size: 15px;">
                    (<a href="{% url 'idea:idea_edit' idea.id %}">Delete</a>)
                </l>
            {% endif %}
        {% if user.is_authenticated %}
            <div style='display:flex;'>
                <form action="{% url 'idea:like_idea' idea.pk %}" method="POST">
                    {% csrf_token %}
                    {% if user in object.like_idea.all %}
                    <button type="submit" name="idea_id" value="{{ idea.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_up</span> {{ total_likes }}</button>
                    {% else %}
                    <button type="submit" name="idea_id" value="{{ idea.id }}" class="btn"><span class="material-icons">thumb_up</span> {{ total_likes }}</button>
                    {% endif %}
                </form>

                <form action="{% url 'idea:unlike_idea' idea.pk %}" method="POST">
                    {% csrf_token %}
                    {% if user in object.unlike_idea.all %}
                    <button type="submit" name="idea_id" value="{{ idea.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_down</span> {{ total_unlikes }}</button> 
                    {% else %}
                    <button type="submit" name="idea_id" value="{{ idea.id }}" class="btn"><span class="material-icons">thumb_down</span> {{ total_unlikes }}</button>
                    {% endif %}
                </form>
            </div>
        {% else %}
        <small>
            {{ total_likes }} Likes & {{ total_unlikes }} Unlike | 
           <a href="{% url 'accounts:login' %}" class="">Log in</a> to like</small>
        {% endif %}
        </p>
        <hr>
        {% if object.header_image %}<br/>    
            <a href="{{ object.header_image.url }}"><img style="display: block; margin-left: auto; margin-right: auto; width: 100%;" src="{{ object.header_image.url }}" ></a><br/><br/>
        {% endif %}
        {{ object.body|safe|linebreaksbr }}
    </div>
    <br/>
    <p>
        {% for category in object.category.all.values %}
            {% if category.slug != 'cryptocurrency'  %}
                <a href="{% url 'price_detail' category.slug %}"><button type="button" class="btn btn-secondary">{{category.slug}}</button></a>
            {% endif %}
        {% endfor %}
        </p>
        <br/>
        <hr>

        <br/>
    <div class="col-md-8 card mb-4 mt-3">
        {% if user.is_authenticated %}
        <a href='{% url "idea:comment_new" idea.pk%}'>Add comment ...</a>
        {% else %}
        <p><a href="{% url 'accounts:login' %}" class="">Log in</a> to add comment</p>
        {% endif %}
        <div class="card-body">
            <h2>{{ object.comments.count }} comments</h2>
            <hr>
            {% for comment in object.comments_idea.all %}
            <div class="comments" style="padding: 10;">
                <p class="font-weight-bold">
                    {{ comment.author }}
                    <span class="text-muted font-weight-normal">
                        {{ comment.created_on }}
                    </span>
                    {% if user.is_authenticated and user.id == idea.author.id %} 
                        <l style="font-size: 15px;">
                            (<a href="{% url 'idea:idea_edit' idea.id %}">Edit</a> | <a href="{% url 'idea:idea_delete' idea.id %}">Delete</a>)
                        </l>
                    {% elif perms.idea.all or perms.idea.change_idea or perms.idea.delete_idea %}
                        <l style="font-size: 15px;">
                            (<a href="{% url 'idea:idea_delete' idea.id %}">Delete</a>)
                        </l>
                    {% endif %}
                </p>
                {{ comment.comment_idea|safe|linebreaks }}
                {% if user.is_authenticated %}
                <div style='display:flex;'>
                    <form action="{% url 'idea:like_comment' idea.pk %}" method="POST">
                        {% csrf_token %}
                        {% if user in comment.like_comment_idea.all %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_up</span> {{ comment.total_likes_comment }}</button>
                        {% else %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons">thumb_up</span> {{ comment.total_likes_comment }}</button>
                        {% endif %}
                    </form>

                    <form action="{% url 'idea:unlike_comment' idea.pk %}" method="POST">
                        {% csrf_token %}
                        {% if user in comment.unlike_comment_idea.all %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons" style="color:blue;">thumb_down</span> {{ comment.total_unlikes_comment }}</button> 
                        {% else %}
                        <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn"><span class="material-icons">thumb_down</span> {{ comment.total_unlikes_comment }}</button> 
                        {% endif %}
                    </form>
                </div>
                {% else %}
                <small>
                    {{ comment.total_likes_comment }} Likes & {{ comment.total_unlikes_comment }} Unlike | 
                    <a href="{% url 'accounts:login' %}" class="">Log in</a> to like</small>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock content %}

templates/idea/idea_edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock title %}

{% block content %}
    <h1>Edit</h1>
    <div class="form-group">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p}}
            <button class="btn btn-info ml-2" type="submit">Update</button>
        </form>
    </div>
{% endblock content %}

templates/idea/idea_list.html
{% extends 'base.html' %}

{% block title %}Idea{% endblock title %}

{% block nav_idea %}
<form class="form-inline ml-auto" style="margin-right: 1%;">
    <a href="{% url 'idea:idea_new' %}" class="btn btn-outline-secondary">Add Idea</a>
</form>
{% endblock nav_idea %}

{% block content %}
</br>
    {% for idea in ideas%}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="/media/{{idea.header_image}}" class="card-img">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">
                                <a href="{% url 'idea:idea_detail' idea.id %}" style="color:#1d1414;">
                                    {{ idea.title }}
                                </a>
                            
                            {% if user.is_authenticated and user.id == idea.author.id %} 
                                <l style="font-size: 15px;">
                                    (<a href="{% url 'idea:idea_edit' idea.id %}">Edit</a> | <a href="{% url 'idea:idea_delete' idea.id %}">Delete</a>)
                                </l>
                            {% elif perms.idea.all or perms.idea.change_idea or perms.idea.delete_idea %}
                                <l style="font-size: 15px;">
                                    (<a href="{% url 'idea:idea_delete' idea.id %}">Delete</a>)
                                </l>
                            {% endif %}
                        </h5>
                        
                        <span class="text-muted">by {{ idea.author }} | {{ idea.datetime }}</span>
                        <p class="card-text">{{ idea.body|safe|truncatewords:"200" }}</p>
                        <p class="card-text"><small class="text-muted">{{idea.date}}</small></p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

templates/idea/idea_new.html
{% extends 'base.html' %}

{% block title %}New Idea{% endblock title %}

{% block content %}
    <h1>Add a Idea</h1>
    <br/>
    <div class="form-group">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <a href="{% url 'category_new' %}">Add a category...</a><br/><br/>
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>
    </div>
{% endblock content %}